[package]
name = "game-of-life"
version = "0.1.0"
authors = ["Christian Bundy <christianbundy@fraction.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
terminal_size= "0.1.13"

